export default {
    GENERATE_TOKEN: '/api/tokenGenrate/jwtToken',
    MOBILE_NUMBER_CHECK: '/api/userAuth/userCheckMobile',
    USER_REGISTRATION: '/api/userAuth/userRegistration',
    SOCIAL_LOGIN: '/api/userAuth/socialLogin',
    GET_ALL_CATEGORY: '/api/category/getAllCategory',
    // GET_SUB_CATEGORY: '/api/category/getSubCategory',
    GET_PRODUCT_CATEGORY: '/api/products/getProductsByCategory',
    GET_PROFILE: '/api/setting/getProfile',
    GET_UPDATE_PROFILE: '/api/setting/updateProfile',
    GET_ADD_EDIT_ADDRESS: '/api/setting/addUpdateAddress',
    UPDATE_ADDRESS: '/api/setting/updateAddress',
    GET_LIST_ADDRESS: '/api/setting/getAddress',
    GET_POPULAR_PRODUCT: '/api/products/popularProduct',
    LANGUAGE_CHANGE: '/api/setting/updateLanguage',
    DASHBORD_PRODUCT: '/api/products/dashboardProduct',
    DELETE_ADDRESS: '/api/setting/deleteAddress',
    GET_SUB_CATEGORY_PRIDUCT: '/api/category/getSubCategoryOrProduct',
    GET_PRODUCT_DETAILS: '/api/products/getProductDetails',
    GET_DASHBORD_PRODUCT_LIST: '/api/products/getProductsListByCategory',
    CONTACT_US: '/api/setting/contactUs',
    ABOUT_US: '/api/setting/aboutUs',
    RATE_US: '/api/setting/rateUs',
    termAndCondition: '/api/setting/termAndCondition',
    USE_COUPON_CODE: '/api/orders/useCouponCode',
    PLACE_ORDER: '/api/orders/placeOrder',
    GET_ORDER_LIST: '/api/orders/getOrderList',
    GET_ORDER_DETAILS: '/api/orders/getOrderDetails',
    PRODUCT_SEARCH: '/api/products/searchProduct',
    GET_TAX_DELIVERY_CHARGE: '/api/orders/getTaxDeliveryCharge',
    RECOMMENDED_PRODUCT: '/api/products/recommendedProducts',
    GET_NOTIFICATION: 'api/notification/getNotification',
    DELETE_NOTIFICATION: "api/notification/deleteNotification",
    CANCEL_ORDER: "api/orders/updateOderStatus"
}
